name: paotm-2020
channels:
  - conda-forge
dependencies:
  - numpy==1.14.6
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - jupyter
  - pip:
    - bmi-python==0.2.7
    - mako
