FROM jupyter/datascience-notebook:python-3.7.6
MAINTAINER Anna van Gils <anna.vangils@deltares.nl>

# Add model to the container (build from teamcity)
COPY ./models/dimrset_lnx64_gnu_66214 /models

# Export model file path to memory
ENV LD_LIBRARY_PATH=/models/lnx64/lib

# Add requirements file
COPY requirements.txt .

RUN pip install -r requirements.txt
