apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: jhub
    name: notebooks
  azureFile:
    secretName: paotm-notebooks-secret
    shareName: notebooks
    readOnly: true
